name = "intakeapp"
main = "index.js"
compatibility_date = "2024-05-26"

[build]
command = "bash build.sh"

[assets]
directory = "output/wwwroot"
not_found_handling = "single-page-application"
include = ["**/*"]

[[d1_databases]]
binding = "DB"
database_name = "intake_db"
database_id = "0e922b28-2410-4426-8a4a-26394a7ef953"

[vars]
ADMIN_USERNAME = "admin"

